Supervise+/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Supervise_.Models;
using System.Diagnostics;
using System.Net.Mail;

namespace Supervise_.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult FacultyHome()
        {
            
                    string sql = "";

                    var builder = WebApplication.CreateBuilder();
                    string conStr = builder.Configuration.GetConnectionString("Supervise_Context");
                    SqlConnection conn = new SqlConnection(conStr);

                    SqlCommand comm;
                    conn.Open();
                    string na = (HttpContext.Session.GetString("Name"));
                    sql = "SELECT COUNT( Id)  FROM sp_GP_Group where Supervisor_Name = '" + na + "' AND statue = 'Supervisor Wait'";
                    comm = new SqlCommand(sql, conn);
                    ViewData["d1"] = (int)comm.ExecuteScalar();
                    ViewData["na"] = na;


            return View();
        }

        public IActionResult GPMemberHome()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Email()
        {
            return View();
        }
        


        [HttpPost, ActionName("Email")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Email(string address, string subject, string body)
        {
            SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com");
            var mail = new MailMessage();
            mail.From = new MailAddress("ccse.projects@gmail.com");
            mail.To.Add(address); // receiver email address
            mail.Subject = subject;
            mail.IsBodyHtml = true;
            mail.Body = body;
            SmtpServer.Port = 587;
            SmtpServer.UseDefaultCredentials = false;
            SmtpServer.Credentials = new System.Net.NetworkCredential("ccse.projects@gmail.com", "fpziukvqekvoqjcx");
            SmtpServer.EnableSsl = true;
            SmtpServer.Send(mail);
            ViewData["Message"] = "Email sent.";
            return View();

        }



        [HttpPost, ActionName("login")]
       
        public async Task<IActionResult> login(string na, string pa)
        {
            var builder = WebApplication.CreateBuilder();
            string conStr = builder.Configuration.GetConnectionString("Supervise_Context");
            SqlConnection conn1 = new SqlConnection(conStr);
            string sql;
            sql = "SELECT * FROM sp_user_account where name ='" + na + "' and  password ='" + pa + "' ";
            SqlCommand comm = new SqlCommand(sql, conn1);
            conn1.Open();
            SqlDataReader reader = comm.ExecuteReader();

            if (reader.Read())
            {
                string id = Convert.ToString((int)reader["Id"]);
                string na1 = (string)reader["name"];
                string ro = (string)reader["role"];
                HttpContext.Session.SetString("userid", id);
                HttpContext.Session.SetString("Name", na1);
                HttpContext.Session.SetString("Role", ro); ;
                reader.Close();
                conn1.Close();
                if (ro == "student")
                    return RedirectToAction("sthome", "Home");
                else if (ro == "instructor")
                    return RedirectToAction("FacultyHome", "Home");
                else if (ro == "gpcm")
                    return RedirectToAction("GPMemberHome", "Home");
                else
                    return View();
            }
            else
            {
                ViewData["Message"] = "wrong user name password";
                return View();
            }

        }



        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult sthome()
        {
            string na = (HttpContext.Session.GetString("Name"));
           
            ViewData["na"] = na;
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }

}

Supervise+/Controllers/sp_GP_GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Supervise_.Data;
using Supervise_.Models;

namespace Supervise_.Controllers
{
    public class sp_GP_GroupController : Controller
    {
        private readonly Supervise_Context _context;

        public sp_GP_GroupController(Supervise_Context context)
        {
            _context = context;
        }

        // GET: sp_GP_Group
        public async Task<IActionResult> Index()
        {
            var gg = await _context.sp_GP_Group.ToListAsync();
            return View(gg);
           
        }

        public async Task<IActionResult> MyIndex()
        {
            string na = (HttpContext.Session.GetString("Name"));
            var grst = await _context.sp_GP_Group.FromSqlRaw("select * from sp_GP_Group where Supervisor_Name = '" + na + "' AND statue = 'Supervisor Wait'").ToListAsync();

            return View(grst);
        }

        // GET: sp_GP_Group/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.sp_GP_Group == null)
            {
                return NotFound();
            }

            var sp_GP_Group = await _context.sp_GP_Group
                .FirstOrDefaultAsync(m => m.id == id);
            if (sp_GP_Group == null)
            {
                return NotFound();
            }

            return View(sp_GP_Group);
        }

        // GET: sp_GP_Group/Create
        public async Task<IActionResult> Create()

        {   
            var grst = await _context.sp_gp_setting.FromSqlRaw("select * from sp_gp_setting where Id = 2").FirstOrDefaultAsync(); 

             int drl =  grst.Dr_supr_limit;
             int msl = grst.Ms_supr_limit;

             var li = await _context.sp_instructor.FromSqlRaw("select * from sp_instructor where (Group_Count < '"+drl+ "' and rank = 'Doctor') or (Group_Count < '"+msl+"' and rank = 'Master')").ToListAsync(); ;
            ViewBag.Superv = li;

            return View();
        }

        // POST: sp_GP_Group/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Supervisor_Name,sthead_name,Year,Project_Project_ProblemDefinition,Project_scope,Project_title,Project_Objective,statue,Registration_code,MassegeToSupervisor")] sp_GP_Group sp_GP_Group)
        {
            if (sp_GP_Group.Project_Project_ProblemDefinition == null) sp_GP_Group.Project_Project_ProblemDefinition = String.Empty;
            if (sp_GP_Group.Project_scope == null) sp_GP_Group.Project_scope = String.Empty;
            if (sp_GP_Group.Project_Objective == null) sp_GP_Group.Project_Objective = String.Empty;
            if (sp_GP_Group.MassegeToSupervisor == null) sp_GP_Group.MassegeToSupervisor = String.Empty;

            
            string stname = (HttpContext.Session.GetString("Name"));
            var cgp = await _context.sp_GP_Group.Where(m => m.sthead_name == stname).FirstOrDefaultAsync();
            if (cgp == null)
            {
                sp_GP_Group.sthead_name = stname;
                int yy = DateTime.Today.Year;
                int mm = DateTime.Today.Month;
                if (mm < 8) {
                    yy = yy - 1;  // 5/2023 belong to 2022
                }

                var st = await _context.sp_student.Where(m => m.Name == stname).FirstOrDefaultAsync();

                sp_GP_Group.gender = st.Gender;
                sp_GP_Group.Year = yy;
                sp_GP_Group.statue = "Supervisor Wait";
                sp_GP_Group.Registration_code = "0";
                _context.Add(sp_GP_Group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            } else
            {
                ViewData["Message"] = "You can not Create two Groups.";
                List<sp_instructor> li = new List<sp_instructor>(); // avoid error
                ViewBag.Superv = li;
                return View();
            }
           

        }
    

        // GET: sp_GP_Group/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var grst = await _context.sp_gp_setting.FromSqlRaw("select * from sp_gp_setting where Id = 2").FirstOrDefaultAsync(); ;

            int drl = grst.Dr_supr_limit;
            int msl = grst.Ms_supr_limit;

            var li = await _context.sp_instructor.FromSqlRaw("select * from sp_instructor where (Group_Count < '" + drl + "' and rank = 'Doctor') or (Group_Count < '" + msl + "' and rank = 'Master')").ToListAsync(); ;
            ViewBag.Superv = li;

            if (id == null || _context.sp_GP_Group == null)
            {
                return NotFound();
            }

            var sp_GP_Group = await _context.sp_GP_Group.FindAsync(id);
            if (sp_GP_Group == null)
            {
                return NotFound();
            }
            if (sp_GP_Group.Project_Project_ProblemDefinition == null) sp_GP_Group.Project_Project_ProblemDefinition = String.Empty;
            if (sp_GP_Group.Project_scope == null) sp_GP_Group.Project_scope = String.Empty;
            if (sp_GP_Group.Project_Objective == null) sp_GP_Group.Project_Objective = String.Empty;
            if (sp_GP_Group.MassegeToSupervisor==null) sp_GP_Group.MassegeToSupervisor = String.Empty;
            return View(sp_GP_Group);
        }

        // POST: sp_GP_Group/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Supervisor_Name,sthead_name,Year,Project_Project_ProblemDefinition,Project_scope,Project_title,Project_Objective,statue,Registration_code,gender,MassegeToSupervisor")] sp_GP_Group sp_GP_Group)
        {
           
                    _context.Update(sp_GP_Group);
                    await _context.SaveChangesAsync();
               
                return RedirectToAction(nameof(Index));
           
        }

        // GET: sp_GP_Group/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.sp_GP_Group == null)
            {
                return NotFound();
            }

            var sp_GP_Group = await _context.sp_GP_Group
                .FirstOrDefaultAsync(m => m.id == id);
            if (sp_GP_Group == null)
            {
                return NotFound();
            }

            return View(sp_GP_Group);
        }

        // POST: sp_GP_Group/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.sp_GP_Group == null)
            {
                return Problem("Entity set 'Supervise_Context.sp_GP_Group'  is null.");
            }
            var sp_GP_Group = await _context.sp_GP_Group.FindAsync(id);
            if (sp_GP_Group != null)
            {
                _context.sp_GP_Group.Remove(sp_GP_Group);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool sp_GP_GroupExists(int id)
        {
          return (_context.sp_GP_Group?.Any(e => e.id == id)).GetValueOrDefault();
        }


     

    }
}

Supervise+/Controllers/sp_studentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Supervise_.Data;
using Supervise_.Models;

namespace Supervise_.Controllers
{
    public class sp_studentController : Controller
    {
        private readonly Supervise_Context _context;

        public sp_studentController(Supervise_Context context)
        {
            _context = context;
        }

        // GET: sp_student
        public async Task<IActionResult> Index()
        {
              return _context.sp_student != null ? 
                          View(await _context.sp_student.ToListAsync()) :
                          Problem("Entity set 'Supervise_Context.sp_student'  is null.");
        }

        // GET: sp_student/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.sp_student == null)
            {
                return NotFound();
            }

            var sp_student = await _context.sp_student
                .FirstOrDefaultAsync(m => m.id == id);
            if (sp_student == null)
            {
                return NotFound();
            }

            return View(sp_student);
        }

        // GET: sp_student/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: sp_student/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,Gender,Email,Phone,Completed_hrs,GPA,Is_pass_web2,Is_pass_pr_mang")] sp_student sp_student)
        {
            if (sp_student.Completed_hrs == "yes" && sp_student.Is_pass_web2 == "yes" && sp_student.Is_pass_pr_mang == "yes")
            {
                sp_student.Name = (HttpContext.Session.GetString("stname"));
                _context.Add(sp_student);
                await _context.SaveChangesAsync();
                return RedirectToAction("sthome","Home");
            } else
            {
                ViewData["message"] = "cannot register need to contact the GP committee ";
                return View(sp_student);


            }
        }

        // GET: sp_student/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.sp_student == null)
            {
                return NotFound();
            }

            var sp_student = await _context.sp_student.FindAsync(id);
            if (sp_student == null)
            {
                return NotFound();
            }
            return View(sp_student);
        }

        // POST: sp_student/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,Gender,Email,Phone,Completed_hrs,GPA,Is_pass_web2,Is_pass_pr_mang")] sp_student sp_student)
        {
            if (id != sp_student.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sp_student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!sp_studentExists(sp_student.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sp_student);
        }

        // GET: sp_student/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.sp_student == null)
            {
                return NotFound();
            }

            var sp_student = await _context.sp_student
                .FirstOrDefaultAsync(m => m.id == id);
            if (sp_student == null)
            {
                return NotFound();
            }

            return View(sp_student);
        }

        // POST: sp_student/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.sp_student == null)
            {
                return Problem("Entity set 'Supervise_Context.sp_student'  is null.");
            }
            var sp_student = await _context.sp_student.FindAsync(id);
            if (sp_student != null)
            {
                _context.sp_student.Remove(sp_student);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool sp_studentExists(int id)
        {
          return (_context.sp_student?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Supervise+/Views/Home/Email.cshtml
@{
    ViewData["Title"] = "Email";
}

<h1>Email</h1>

<body>


    <form asp-action="email">
        <div class="form-group">
            <label class="control-label"> Address</label>
            <input name="address" class="form-control" /> <br />
        </div>
        <div class="form-group">
            <label for="body" class="control-label"> Subject</label>
            <input name="body" class="form-control" /> <br />
        </div>
        <div class="form-group">
            <label for="subject" class="control-label"> Body</label>
            <textarea  name="subject" rows="4" cols="50"> </textarea>


        </div>
        <input type="submit" value="Send" class="btn btn-default" />
        <p> @ViewData["message"]</p>
    </form>



    </body>

Supervise+/Views/Home/FacultyHome.cshtml
<h1 style="text-align:center">Instructor Home Page </h1>     <h2 style="text-align:center; color:darkblue">welcome @ViewData["na"]  </h2> 
<body>

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/f1.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/f2.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                <a asp-controller="sp_instructor" asp-action="Edit"><img src="~/images/f3.png" alt="" width="250"></a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <a asp-controller="sp_gp_ideas" asp-action="Index"><img src="~/images/project ideas2.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                <a asp-controller="sp_GP_Group" asp-action="MyIndex"><img src="~/images/f5.png" alt="" width="250"> @ViewData["d1"] </a> 
                     
            </div>

            </div>

        </div>
    </div>
</body>

Supervise+/Views/Home/GPMemberHome.cshtml
@{
    ViewData["Title"] = "GPMemberHome";
}

<h1>GP Committee Home</h1>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/gp1.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/gp2.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                <a asp-controller="sp_user_account" asp-action="Index"><img src="~/images/gp3.png" alt="" width="250"></a>
            </div>
              
        </div>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/gp4.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                <a asp-controller="sp_gp_setting" asp-action="Create"><img src="~/images/gp5.png" alt="" width="250"></a>
            </div>
              <div class="col-md-3">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/gp6.png" alt="" width="250"></a>
            </div>

            </div>

             <div class="row"> 
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/gp7.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/gp8.png" alt="" width="250"></a>
            </div>
              <div class="col-md-3">
                <a asp-controller="sp_faculity_roles" asp-action="Index"><img src="~/images/gp9.png" alt="" width="250"></a>
            </div>

             <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/gp10.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/gp11.png" alt="" width="250"></a>
            </div>
              

            </div>
        </div>
    </div>
</body>

Supervise+/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="display-4">
    <a asp-action="login"> 
        <img scr="~/images/Students"height="30" />

    </a>
</div>
     

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Supervise+/Views/Home/login.cshtml
@{
    ViewData["Title"] = "login";
}

<h2>Login</h2>
<form asp-action="Login">
    <div class="form-group">
        <label  class="control-label"> user Name</label>
        <input name="na" class="form-control" />
    </div>
    <div class="form-group">
        <label for="pa" class="control-label"> user Password</label>
        <input name="pa" class="form-control" /> <br />
    </div>
    <input type="submit" value="Login" class="btn btn-primary" />
    <p style="color:red"> @ViewData["message"]</p>
</form>

<a asp-controller="sp_user_account" asp-action="Create">Register here </a>
 

Supervise+/Views/Home/sthome.cshtml
<head> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<h1 style="text-align:center">Student Home Page </h1>     <h2 style="text-align:center; color:darkblue">welcome @ViewData["na"]  </h2> 
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <a asp-controller="sp_student" asp-action="Index"><img src="~/Image/icon1.png" alt="" width="250"></a>
               
            </div>
            <div class="col-md-3">
               <a asp-controller="sp_student" asp-action="Index"><img src="~/Image/icon2.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                <a asp-controller="sp_student" asp-action="Index"><img src="~/Image/icon3.png" alt="" width="250"></a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-3">
                 <a asp-controller="sp_student" asp-action="Index"><img src="~/Image/icon4.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                 <a asp-controller="sp_GP_Group" asp-action="Create"><img src="~/Image/icon5.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                 <a asp-controller="sp_gp_ideas" asp-action="Index"><img src="~/Image/icon6.png" alt="" width="250"></a>
            </div>
        </div>
    </div>
    <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-3">
                 <a asp-controller="sp_instructor" asp-action="Index"><img src="~/Image/icon7.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                 <a asp-controller="sp_student" asp-action="Index"><img src="~/Image/icon8.png" alt="" width="250"></a>
            </div>
            <div class="col-md-3">
                 <a asp-controller="sp_gp_ideas" asp-action="Index"><img src="~/Image/icon9.png" alt="" width="250"></a>
            </div>
        </div>
    </div>
     <div class="row">
            <div class="col-md-3"></div>
             <div class="col-md-3">
                  <a asp-controller="sp_GP_Group" asp-action="Index"><img src="~/Image/icon10.png" alt="" width="300"></a>
                   </div>
                    <div class="col-md-3"></div>
        </div>
    </div>
</body>